import { Category, Product, Service } from '@/types';

// Prefix asset paths with the deployment base path (e.g. /rahan on GitHub Pages)
export const withBase = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH || ''}${path}`;

// Store WhatsApp number in international format (0221 93290358 → +49)
export const WHATSAPP_PHONE = '4922193290358';

// Köln postcode range — deliveries are only made within the city
export const KOELN_PLZ = { min: 50667, max: 51149 };

export const MAPS_URL =
  'https://maps.google.com/maps/place//data=!4m2!3m1!1s0x47bf2300ca89d765:0x861c99e70b9ee4d9?entry=s&sa=X&ved=2ahUKEwjn09_ttLyVAxWaSKQEHep8K0IQ4kB6BAgbEAA&hl=en';

export const MAP_EMBED =
  'https://maps.google.com/maps?q=Luxemburger+Str.+12%2C+50674+K%C3%B6ln%2C+Germany&hl=de&z=17&output=embed';

export const CATS: Category[] = [
  { id: 1,  fa: 'نوشابه', de: 'Erfrischungsgetränke', emoji: '', color: '#A32222', bg: '#F8E5E1', img: '/images/categories/softdrinks.webp' },
  { id: 2,  fa: 'آب معدنی', de: 'Mineralwasser', emoji: '', color: '#166044', bg: '#DCE9E2', img: '/images/categories/water.webp' },
  { id: 3,  fa: 'آبمیوه', de: 'Säfte', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/products/oranges.webp' },
  { id: 4,  fa: 'دلستر', de: 'Malzgetränke', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/softdrinks.webp' },
  { id: 5,  fa: 'عرقیات', de: 'Kräuterdestillate', emoji: '', color: '#166044', bg: '#DCE9E2', img: '/images/categories/herbal.webp' },
  { id: 6,  fa: 'چای و دمنوش', de: 'Tee & Kräutertee', emoji: '', color: '#0E3B2A', bg: '#E8EEEA', img: '/images/products/tea.webp' },
  { id: 7,  fa: 'برنج', de: 'Reis', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/products/rice.webp' },
  { id: 8,  fa: 'حبوبات', de: 'Hülsenfrüchte', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/legumes.webp' },
  { id: 9,  fa: 'ادویه‌جات', de: 'Gewürze', emoji: '', color: '#A32222', bg: '#F8E5E1', img: '/images/categories/spices.webp' },
  { id: 10, fa: 'رب و چاشنی', de: 'Mark & Saucen', emoji: '', color: '#A32222', bg: '#F8E5E1', img: '/images/categories/sauces.webp' },
  { id: 11, fa: 'ترشیجات', de: 'Eingelegtes & Oliven', emoji: '', color: '#166044', bg: '#DCE9E2', img: '/images/categories/jam.webp' },
  { id: 12, fa: 'مواد غذایی خشک', de: 'Trockenwaren', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/pasta.webp' },
  { id: 13, fa: 'لبنیات', de: 'Milchprodukte', emoji: '', color: '#166044', bg: '#DCE9E2', img: '/images/categories/milk.webp' },
  { id: 14, fa: 'روغن', de: 'Speiseöle', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/oil.webp' },
  { id: 15, fa: 'گوشت و پروتئین حلال', de: 'Halal Fleisch & Protein', emoji: '', color: '#A32222', bg: '#F8E5E1', img: '/images/categories/meat.webp' },
  { id: 16, fa: 'غذاهای آماده', de: 'Fertiggerichte', emoji: '', color: '#5A5A55', bg: '#EDEDEC', img: '/images/categories/cans.webp' },
  { id: 17, fa: 'بیسکویت و شیرینی', de: 'Kekse & Gebäck', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/biscuits.webp' },
  { id: 18, fa: 'شکلات', de: 'Schokolade', emoji: '', color: '#A32222', bg: '#F8E5E1', img: '/images/categories/chocolate.webp' },
  { id: 19, fa: 'تنقلات و آجیل', de: 'Snacks & Nüsse', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/snacks.webp' },
  { id: 20, fa: 'شیرینی سنتی', de: 'Traditionelle Süßigkeiten', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/sweets.webp' },
  { id: 21, fa: 'نان', de: 'Brot', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/products/bread.webp' },
  { id: 22, fa: 'سبزیجات تازه', de: 'Frisches Gemüse', emoji: '', color: '#0E3B2A', bg: '#E8EEEA', img: '/images/categories/broccoli.webp' },
  { id: 23, fa: 'میوه', de: 'Frisches Obst', emoji: '', color: '#A32222', bg: '#F8E5E1', img: '/images/products/apples.webp' },
  { id: 24, fa: 'شوینده و بهداشتی', de: 'Reinigung & Hygiene', emoji: '', color: '#166044', bg: '#DCE9E2', img: '/images/categories/detergent.webp' },
  { id: 25, fa: 'لوازم یکبار مصرف', de: 'Einweggeschirr', emoji: '', color: '#5A5A55', bg: '#EDEDEC', img: '/images/categories/paper.webp' },
  { id: 26, fa: 'محصولات مناسبتی', de: 'Saisonale Produkte', emoji: '', color: '#9A742A', bg: '#F7EDD0', img: '/images/categories/buns.webp' },
  { id: 27, fa: 'سایر اقلام', de: 'Sonstiges', emoji: '', color: '#0E3B2A', bg: '#E8EEEA', img: '/images/categories/coffee.webp' },
];

export const PRODUCTS: Product[] = [
  { id: 1,   fa: 'کوکاکولا', de: 'Coca-Cola', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 9,   fa: 'آب معدنی گازدار', de: 'Mineralwasser mit Kohlensäure', catId: 2,  catFa: 'آب معدنی', catDe: 'Mineralwasser', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/water.webp' },
  { id: 12,  fa: 'آبمیوه سن‌ایچ', de: 'Sunich Fruchtsaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 22,  fa: 'دلستر لیمویی', de: 'Malzgetränk Zitrone', catId: 4,  catFa: 'دلستر', catDe: 'Malzgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 27,  fa: 'گلاب', de: 'Rosenwasser', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 35,  fa: 'چای احمد', de: 'Ahmad Tea', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 44,  fa: 'برنج هاشمی', de: 'Hashemi-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 53,  fa: 'لوبیا چیتی', de: 'Pintobohnen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 62,  fa: 'زردچوبه', de: 'Kurkuma', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 76,  fa: 'رب گوجه‌فرنگی', de: 'Tomatenmark', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 87,  fa: 'خیارشور', de: 'Salzgurken', catId: 11, catFa: 'ترشیجات', catDe: 'Eingelegtes & Oliven', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/jam.webp' },
  { id: 93,  fa: 'ماکارونی', de: 'Nudeln', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 102, fa: 'ماست', de: 'Joghurt', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: 3.49, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/yogurt.webp' },
  { id: 112, fa: 'روغن مایع', de: 'Pflanzenöl', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/oil.webp' },
  { id: 117, fa: 'گوشت گوسفند', de: 'Lammfleisch', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 128, fa: 'سبزی قورمه', de: 'Ghormeh-Kräuter', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 140, fa: 'ساقه طلایی', de: 'Saghe Talaei Kekse', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: 1.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/saghe-talaei.webp' },
  { id: 148, fa: 'کیت‌کت', de: 'KitKat', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/chocolate.webp' },
  { id: 154, fa: 'پفک', de: 'Pofak (Käsesnack)', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 166, fa: 'گز', de: 'Gaz (Persischer Nougat)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 176, fa: 'نان لواش', de: 'Lavash-Brot', catId: 21, catFa: 'نان', catDe: 'Brot', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 183, fa: 'سبزی خوردن', de: 'Frische Kräutermischung', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 196, fa: 'انار', de: 'Granatapfel', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 206, fa: 'مایع ظرفشویی', de: 'Spülmittel', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 217, fa: 'لیوان یکبار مصرف', de: 'Einwegbecher', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 226, fa: 'سبزه نوروز', de: 'Norooz-Sabzeh', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 235, fa: 'قهوه', de: 'Kaffee', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 2,   fa: 'پپسی', de: 'Pepsi', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 10,  fa: 'آب معدنی بدون گاز', de: 'Mineralwasser ohne Kohlensäure', catId: 2,  catFa: 'آب معدنی', catDe: 'Mineralwasser', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/water.webp' },
  { id: 13,  fa: 'آبمیوه تکدانه', de: 'Takdaneh Fruchtsaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 23,  fa: 'دلستر هلو', de: 'Malzgetränk Pfirsich', catId: 4,  catFa: 'دلستر', catDe: 'Malzgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 28,  fa: 'عرق نعناع', de: 'Minzdestillat', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 36,  fa: 'چای دوغزال', de: 'Do Ghazal Tee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 45,  fa: 'برنج طارم', de: 'Tarom-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: 8.49, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 54,  fa: 'لوبیا قرمز', de: 'Rote Bohnen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 63,  fa: 'فلفل سیاه', de: 'Schwarzer Pfeffer', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 77,  fa: 'رب انار', de: 'Granatapfelmark', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 88,  fa: 'زیتون', de: 'Oliven', catId: 11, catFa: 'ترشیجات', catDe: 'Eingelegtes & Oliven', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/jam.webp' },
  { id: 94,  fa: 'رشته آشی', de: 'Ash-Nudeln', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 103, fa: 'دوغ', de: 'Doogh (Joghurtgetränk)', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 113, fa: 'روغن سرخ‌کردنی', de: 'Frittieröl', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/oil.webp' },
  { id: 118, fa: 'گوشت گوساله', de: 'Rindfleisch', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 129, fa: 'سبزی آش', de: 'Ash-Kräuter', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 141, fa: 'بیسکویت مادر', de: 'Madar Kekse', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 149, fa: 'مارس', de: 'Mars', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/chocolate.webp' },
  { id: 155, fa: 'چیپس', de: 'Chips', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 167, fa: 'سوهان', de: 'Sohan', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 177, fa: 'نان سنگک', de: 'Sangak-Brot', catId: 21, catFa: 'نان', catDe: 'Brot', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 184, fa: 'جعفری', de: 'Petersilie', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 197, fa: 'خرمالو', de: 'Kaki', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 207, fa: 'مایع لباسشویی', de: 'Flüssigwaschmittel', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 218, fa: 'بشقاب یکبار مصرف', de: 'Einwegteller', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 227, fa: 'سنجد', de: 'Senjed', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 236, fa: 'نسکافه', de: 'Nescafé', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 3,   fa: 'فانتا', de: 'Fanta', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 11,  fa: 'آب طعم‌دار', de: 'Aromatisiertes Wasser', catId: 2,  catFa: 'آب معدنی', catDe: 'Mineralwasser', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/water.webp' },
  { id: 14,  fa: 'رانی', de: 'Rani Fruchtsaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 24,  fa: 'دلستر استوایی', de: 'Malzgetränk Tropical', catId: 4,  catFa: 'دلستر', catDe: 'Malzgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 29,  fa: 'عرق بیدمشک', de: 'Moschusweiden-Destillat', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 37,  fa: 'چای گلستان', de: 'Golestan Tee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 46,  fa: 'برنج صدری', de: 'Sadri-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 55,  fa: 'لوبیا سفید', de: 'Weiße Bohnen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 64,  fa: 'فلفل قرمز', de: 'Chilipulver', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 78,  fa: 'رب فلفل', de: 'Paprikamark', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 89,  fa: 'ترشی مخلوط', de: 'Gemischtes Eingelegtes', catId: 11, catFa: 'ترشیجات', catDe: 'Eingelegtes & Oliven', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/jam.webp' },
  { id: 95,  fa: 'رشته پلویی', de: 'Reshteh Polowi', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 104, fa: 'پنیر ایرانی', de: 'Iranischer Käse', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: 4.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/cheese.webp' },
  { id: 114, fa: 'روغن زیتون', de: 'Olivenöl', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/oil.webp' },
  { id: 119, fa: 'مرغ', de: 'Hähnchen', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 130, fa: 'سبزی کوکو', de: 'Kuku-Kräuter', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 142, fa: 'پتی‌بور', de: 'Petit Beurre', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 150, fa: 'اسنیکرز', de: 'Snickers', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/chocolate.webp' },
  { id: 156, fa: 'تخمه', de: 'Kerne', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 168, fa: 'پولکی', de: 'Poolaki', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 178, fa: 'نان بربری', de: 'Barbari-Brot', catId: 21, catFa: 'نان', catDe: 'Brot', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 185, fa: 'گشنیز', de: 'Koriander', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 198, fa: 'خرما', de: 'Datteln', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 208, fa: 'پودر لباسشویی', de: 'Waschpulver', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 219, fa: 'قاشق یکبار مصرف', de: 'Einweglöffel', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 228, fa: 'سمنو نوروزی', de: 'Norooz-Samanu', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 237, fa: 'کاپوچینو', de: 'Cappuccino', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 4,   fa: 'اسپرایت', de: 'Sprite', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 15,  fa: 'دلستر میوه‌ای', de: 'Fruchtiges Malzgetränk', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 25,  fa: 'دلستر کلاسیک', de: 'Malzgetränk Klassisch', catId: 4,  catFa: 'دلستر', catDe: 'Malzgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 30,  fa: 'عرق کاسنی', de: 'Zichorien-Destillat', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 38,  fa: 'چای محمود', de: 'Mahmood Tee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 47,  fa: 'برنج دم‌سیاه', de: 'Domsiah-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 56,  fa: 'لوبیا چشم‌بلبلی', de: 'Augenbohnen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 65,  fa: 'دارچین', de: 'Zimt', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 79,  fa: 'آبغوره', de: 'Verjus', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 90,  fa: 'ترشی لیته', de: 'Torshi Liteh', catId: 11, catFa: 'ترشیجات', catDe: 'Eingelegtes & Oliven', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/jam.webp' },
  { id: 96,  fa: 'ورمیشل', de: 'Fadennudeln', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 105, fa: 'پنیر لیقوان', de: 'Lighvan-Käse', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 115, fa: 'روغن کنجد', de: 'Sesamöl', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/oil.webp' },
  { id: 120, fa: 'جوجه کباب', de: 'Jujeh Kabab', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 131, fa: 'پیاز داغ', de: 'Röstzwiebeln', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 143, fa: 'بیسکویت کرم‌دار', de: 'Cremekekse', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 151, fa: 'میلکا', de: 'Milka', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/chocolate.webp' },
  { id: 157, fa: 'بادام', de: 'Mandeln', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 169, fa: 'نبات', de: 'Kandiszucker', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 179, fa: 'نان تافتون', de: 'Taftoon-Brot', catId: 21, catFa: 'نان', catDe: 'Brot', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 186, fa: 'شوید', de: 'Dill', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 199, fa: 'سیب', de: 'Äpfel', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: 2.79, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 209, fa: 'سفیدکننده', de: 'Bleichmittel', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 220, fa: 'چنگال یکبار مصرف', de: 'Einweggabeln', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 229, fa: 'آجیل شب یلدا', de: 'Yalda-Nussmischung', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 238, fa: 'قند', de: 'Würfelzucker', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 5,   fa: 'سون‌آپ', de: '7Up', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 16,  fa: 'آب پرتقال', de: 'Orangensaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 26,  fa: 'دلستر آناناس', de: 'Malzgetränk Ananas', catId: 4,  catFa: 'دلستر', catDe: 'Malzgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 31,  fa: 'عرق بهارنارنج', de: 'Orangenblütenwasser', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 39,  fa: 'چای سیاه', de: 'Schwarzer Tee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: 6.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 48,  fa: 'برنج شیرودی', de: 'Shirudi-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 57,  fa: 'عدس', de: 'Linsen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 66,  fa: 'هل', de: 'Kardamom', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 80,  fa: 'آبلیمو', de: 'Zitronensaft', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 91,  fa: 'سیر ترشی', de: 'Eingelegter Knoblauch', catId: 11, catFa: 'ترشیجات', catDe: 'Eingelegtes & Oliven', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/jam.webp' },
  { id: 97,  fa: 'آرد سفید', de: 'Weizenmehl', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 106, fa: 'خامه', de: 'Sahne', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 116, fa: 'روغن حیوانی', de: 'Butterschmalz', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/oil.webp' },
  { id: 255, fa: 'روغن نباتی السعد ۱ لیتر', de: 'Alssad Pflanzen-Ghee 1 L', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: 7.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/ghee-alssad-1l.webp' },
  { id: 256, fa: 'روغن نباتی السعد ۲ لیتر', de: 'Alssad Pflanzen-Ghee 2 L', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: 12.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/ghee-alssad-2l.webp' },
  { id: 258, fa: 'روغن حیوانی خانم ۵۰۰ گرم', de: 'Khanum Pure Ghee 500 g', catId: 14, catFa: 'روغن', catDe: 'Speiseöle', price: 9.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/ghee-khanum-500g.webp' },
  { id: 121, fa: 'کباب لقمه', de: 'Koobideh Kabab', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 132, fa: 'بادمجان کبابی', de: 'Gegrillte Auberginen', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 144, fa: 'ویفر', de: 'Waffeln', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 152, fa: 'تابلرون', de: 'Toblerone', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/chocolate.webp' },
  { id: 158, fa: 'پسته', de: 'Pistazien', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 170, fa: 'نقل', de: 'Noghl', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 180, fa: 'نان پیتا', de: 'Pitabrot', catId: 21, catFa: 'نان', catDe: 'Brot', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 187, fa: 'نعناع', de: 'Minze', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 200, fa: 'پرتقال', de: 'Orangen', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: 2.49, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 210, fa: 'دستمال کاغذی', de: 'Papiertaschentücher', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 221, fa: 'کارد یکبار مصرف', de: 'Einwegmesser', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 230, fa: 'خرمای مناسبتی', de: 'Festtags-Datteln', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 239, fa: 'شکر', de: 'Zucker', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 6,   fa: 'ردبول', de: 'Red Bull', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 17,  fa: 'آب انبه', de: 'Mangosaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 32,  fa: 'عرق شاتره', de: 'Erdrauch-Destillat', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 40,  fa: 'چای سبز', de: 'Grüner Tee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 49,  fa: 'برنج فجر', de: 'Fajr-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 58,  fa: 'لپه', de: 'Gelbe Spalterbsen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 67,  fa: 'زنجبیل', de: 'Ingwer', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 81,  fa: 'سرکه', de: 'Essig', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 92,  fa: 'شور', de: 'Salzgemüse', catId: 11, catFa: 'ترشیجات', catDe: 'Eingelegtes & Oliven', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/jam.webp' },
  { id: 98,  fa: 'آرد نخودچی', de: 'Kichererbsenmehl', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 107, fa: 'شیر', de: 'Milch', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 122, fa: 'سوسیس حلال', de: 'Halal Würstchen', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 133, fa: 'کشک بادمجان', de: 'Kashk-e Bademjan', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 145, fa: 'کیک یزدی', de: 'Yazdi-Kuchen', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 153, fa: 'شکلات ایرانی', de: 'Iranische Schokolade', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/chocolate.webp' },
  { id: 252, fa: 'شکلات رنگارنگ مینو', de: 'Minoo Rangarang Toffee', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: 5.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rangarang.webp' },
  { id: 260, fa: 'شکلات کنفت ۵۰۰ گرم', de: 'Konfekt-Schokolade 500 g', catId: 18, catFa: 'شکلات', catDe: 'Schokolade', price: 4.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/konfekt-choc.webp' },
  { id: 159, fa: 'گردو', de: 'Walnüsse', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/walnuts.webp' },
  { id: 171, fa: 'باقلوا', de: 'Baklava', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 181, fa: 'نان تست', de: 'Toastbrot', catId: 21, catFa: 'نان', catDe: 'Brot', price: 2.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 188, fa: 'تره', de: 'Lauch', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 201, fa: 'موز', de: 'Bananen', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 211, fa: 'دستمال توالت', de: 'Toilettenpapier', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 222, fa: 'سفره یکبار مصرف', de: 'Einweg-Tischdecke', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 231, fa: 'زولبیا و بامیه', de: 'Zoolbia & Bamieh', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 240, fa: 'نبات چوبی', de: 'Kandiszucker-Sticks', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 7,   fa: 'مانستر', de: 'Monster Energy', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 18,  fa: 'آب آناناس', de: 'Ananassaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 33,  fa: 'خاکشیر', de: 'Khakshir-Samen', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 41,  fa: 'دمنوش بابونه', de: 'Kamillentee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 50,  fa: 'برنج باسماتی هند', de: 'Indischer Basmati-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 59,  fa: 'نخود', de: 'Kichererbsen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 68,  fa: 'زیره', de: 'Kreuzkümmel', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 82,  fa: 'سس مایونز', de: 'Mayonnaise', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 99,  fa: 'آرد برنج', de: 'Reismehl', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 108, fa: 'کره', de: 'Butter', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 123, fa: 'کالباس حلال', de: 'Halal Aufschnitt', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 134, fa: 'سمنو', de: 'Samanu', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 146, fa: 'کلوچه', de: 'Kolucheh', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 160, fa: 'فندق', de: 'Haselnüsse', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 172, fa: 'قطاب سنتی', de: 'Traditioneller Ghotab', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 182, fa: 'تورتیلا', de: 'Tortilla', catId: 21, catFa: 'نان', catDe: 'Brot', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/bread.webp' },
  { id: 189, fa: 'ریحان', de: 'Basilikum', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 202, fa: 'هندوانه', de: 'Wassermelone', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 212, fa: 'کیسه زباله', de: 'Müllbeutel', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 223, fa: 'فویل آلومینیوم', de: 'Alufolie', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 232, fa: 'شیرینی عید', de: 'Festgebäck', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 241, fa: 'عسل', de: 'Honig', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: 7.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/honey.webp' },
  { id: 8,   fa: 'نوشابه بدون شکر', de: 'Zuckerfreie Erfrischungsgetränke', catId: 1,  catFa: 'نوشابه', catDe: 'Erfrischungsgetränke', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/softdrinks.webp' },
  { id: 19,  fa: 'آب هلو', de: 'Pfirsichsaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 34,  fa: 'تخم شربتی', de: 'Basilikumsamen', catId: 5,  catFa: 'عرقیات', catDe: 'Kräuterdestillate', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/herbal.webp' },
  { id: 42,  fa: 'گل گاوزبان', de: 'Borretschblüten-Tee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 51,  fa: 'برنج پاکستانی', de: 'Pakistanischer Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 60,  fa: 'ماش', de: 'Mungbohnen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 69,  fa: 'سماق', de: 'Sumach', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 83,  fa: 'کچاپ', de: 'Ketchup', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 100, fa: 'نشاسته', de: 'Speisestärke', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 109, fa: 'کشک', de: 'Kashk', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 124, fa: 'همبرگر', de: 'Hamburger', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 135, fa: 'دلمه', de: 'Dolma (Gefüllte Weinblätter)', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 147, fa: 'قطاب', de: 'Ghotab', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/biscuits.webp' },
  { id: 253, fa: 'بیسکویت فرخنده کنجد و شوید', de: 'Farkhondeh Kekse (Sesam & Dill)', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: 4.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/biscuit-farkhondeh.webp' },
  { id: 261, fa: 'کلوچه نادری با مغز گردو', de: 'Naderi Kekse mit Walnussfüllung', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: 1.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/naderi-walnut.webp' },
  { id: 263, fa: 'بیسکویت کرم‌دار پرتقالی', de: 'Cremekekse mit Orangengeschmack', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/biscuit-orange-cream.webp' },
  { id: 264, fa: 'بیسکویت فرخنده با طعم موز', de: 'Farkhondeh Kekse mit Bananengeschmack', catId: 17, catFa: 'بیسکویت و شیرینی', catDe: 'Kekse & Gebäck', price: 4.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/biscuit-farkhondeh-banana.webp' },
  { id: 161, fa: 'کشمش', de: 'Rosinen', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 173, fa: 'مسقطی', de: 'Masghati', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 190, fa: 'اسفناج', de: 'Spinat', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 203, fa: 'طالبی', de: 'Zuckermelone', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 213, fa: 'شامپو', de: 'Shampoo', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 224, fa: 'سلفون', de: 'Frischhaltefolie', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 233, fa: 'شمع', de: 'Kerzen', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 242, fa: 'مربا', de: 'Marmelade', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 20,  fa: 'آب آلبالو', de: 'Sauerkirschsaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 43,  fa: 'چای ترش', de: 'Hibiskustee', catId: 6,  catFa: 'چای و دمنوش', catDe: 'Tee & Kräutertee', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tea.webp' },
  { id: 52,  fa: 'برنج ترکی', de: 'Türkischer Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice.webp' },
  { id: 254, fa: 'برنج شاهان درباری', de: 'Shahan Darbari Basmati-Reis', catId: 7,  catFa: 'برنج', catDe: 'Reis', price: 17.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/rice-shahan.webp' },
  { id: 61,  fa: 'سویا', de: 'Sojabohnen', catId: 8,  catFa: 'حبوبات', catDe: 'Hülsenfrüchte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/legumes.webp' },
  { id: 70,  fa: 'گلپر', de: 'Golpar (Persischer Bärenklau)', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 84,  fa: 'خردل', de: 'Senf', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 101, fa: 'آرد سمولینا', de: 'Hartweizengrieß', catId: 12, catFa: 'مواد غذایی خشک', catDe: 'Trockenwaren', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/pasta.webp' },
  { id: 110, fa: 'پنیر پیتزا', de: 'Pizzakäse', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/milk.webp' },
  { id: 125, fa: 'فیله مرغ', de: 'Hähnchenfilet', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 136, fa: 'خورش قورمه‌سبزی', de: 'Ghormeh Sabzi Eintopf', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 162, fa: 'انجیر خشک', de: 'Getrocknete Feigen', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 174, fa: 'باسلوق', de: 'Basloogh', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 191, fa: 'بادمجان', de: 'Auberginen', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 204, fa: 'انگور', de: 'Trauben', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: 3.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/grapes.webp' },
  { id: 214, fa: 'صابون', de: 'Seife', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 225, fa: 'کیسه فریزر', de: 'Gefrierbeutel', catId: 25, catFa: 'لوازم یکبار مصرف', catDe: 'Einweggeschirr', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/paper.webp' },
  { id: 234, fa: 'سفره هفت‌سین', de: 'Haft-Sin Tischdecke', catId: 26, catFa: 'محصولات مناسبتی', catDe: 'Saisonale Produkte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/buns.webp' },
  { id: 243, fa: 'ارده', de: 'Sesammus (Tahini)', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 21,  fa: 'آب انار', de: 'Granatapfelsaft', catId: 3,  catFa: 'آبمیوه', catDe: 'Säfte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/oranges.webp' },
  { id: 71,  fa: 'زعفران', de: 'Safran', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 85,  fa: 'سس تند', de: 'Scharfe Sauce', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 111, fa: 'تخم‌مرغ', de: 'Eier', catId: 13, catFa: 'لبنیات', catDe: 'Milchprodukte', price: 3.29, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/eggs.webp' },
  { id: 126, fa: 'ماهی', de: 'Fisch', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 137, fa: 'خورش قیمه', de: 'Gheimeh Eintopf', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 163, fa: 'برگه زردآلو', de: 'Getrocknete Aprikosen', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 175, fa: 'راحت‌الحلقوم', de: 'Lokum', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sweets.webp' },
  { id: 259, fa: 'غریبه شهیه با وانیل و بادام', de: 'Shahia Ghorayeba (Vanille & Mandeln)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 7.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/ghorayeba-shahia.webp' },
  { id: 262, fa: 'سوهان تخت خودکار', de: 'Khodkar Sohan Takht', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 8.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/sohan-khodkar.webp' },
  { id: 267, fa: 'پشمک زعفرانی حاج عبدالله', de: 'Hajabdolo Saffran-Pashmak', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 6.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/pashmak-saffron.webp' },
  { id: 268, fa: 'پشمک لقمه‌ای زعفرانی حاج عبدالله (۱۷ عددی)', de: 'Hajabdolo Saffran-Pashmak Häppchen (17 Stück)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 7.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/pashmak-box-17.webp' },
  { id: 269, fa: 'گز کرمانی جعبه نارنجی', de: 'Kermani Gaz Geschenkbox (orange)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 9.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/gaz-kermani-orange.webp' },
  { id: 270, fa: 'گز کرمانی جعبه ترمه فیروزه‌ای', de: 'Kermani Gaz Geschenkbox (Termeh türkis)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 10.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/gaz-kermani-termeh.webp' },
  { id: 271, fa: 'گز کرمانی جعبه اصفهان', de: 'Kermani Gaz Geschenkbox (Esfahan)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 10.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/gaz-kermani-esfahan.webp' },
  { id: 272, fa: 'گز کرمانی جعبه طلایی', de: 'Kermani Gaz Geschenkbox (gold)', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 11.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/gaz-kermani-gold.webp' },
  { id: 273, fa: 'گز شروین', de: 'Shervin Gaz', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 12.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/gaz-shervin.webp' },
  { id: 274, fa: 'گز لقمه‌ای ویونا ۲۵٪ مغز پسته', de: 'Viuna Gaz-Häppchen 25% Pistazie', catId: 20, catFa: 'شیرینی سنتی', catDe: 'Traditionelle Süßigkeiten', price: 9.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/viuna-box.webp' },
  { id: 192, fa: 'گوجه‌فرنگی', de: 'Tomaten', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: 2.49, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/tomatoes.webp' },
  { id: 205, fa: 'کیوی', de: 'Kiwi', catId: 23, catFa: 'میوه', catDe: 'Frisches Obst', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apples.webp' },
  { id: 215, fa: 'خمیردندان', de: 'Zahnpasta', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 244, fa: 'حلوا ارده', de: 'Halva', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 72,  fa: 'آویشن', de: 'Thymian', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 86,  fa: 'سس سیر', de: 'Knoblauchsauce', catId: 10, catFa: 'رب و چاشنی', catDe: 'Mark & Saucen', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/sauces.webp' },
  { id: 127, fa: 'میگو', de: 'Garnelen', catId: 15, catFa: 'گوشت و پروتئین حلال', catDe: 'Halal Fleisch & Protein', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/meat.webp' },
  { id: 138, fa: 'فسنجان', de: 'Fesenjan', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 164, fa: 'لواشک', de: 'Lavashak (Fruchtleder)', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 193, fa: 'خیار', de: 'Gurken', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: 1.99, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/cucumbers.webp' },
  { id: 216, fa: 'مسواک', de: 'Zahnbürste', catId: 24, catFa: 'شوینده و بهداشتی', catDe: 'Reinigung & Hygiene', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/detergent.webp' },
  { id: 245, fa: 'کره بادام‌زمینی', de: 'Erdnussbutter', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 73,  fa: 'کاری', de: 'Curry', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 139, fa: 'کنسرو ایرانی', de: 'Iranische Konserven', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/cans.webp' },
  { id: 257, fa: 'سبزی سرخ‌شده آمو فود', de: 'Amu Food Gebratene Kräuter', catId: 16, catFa: 'غذاهای آماده', catDe: 'Fertiggerichte', price: 3.50, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/sabzi-amufood.webp' },
  { id: 165, fa: 'آلوچه', de: 'Aloocheh', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/snacks.webp' },
  { id: 250, fa: 'عناب درشت', de: 'Große Jujube (Annab)', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/jujube-large.webp' },
  { id: 251, fa: 'عناب خشک', de: 'Getrocknete Jujube (Annab)', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/jujube-dried.webp' },
  { id: 265, fa: 'قیسی واحدی ۷۰۰ گرم', de: 'Gheisi Trockenaprikosen 700 g', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: 15.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/gheisi-700g.webp' },
  { id: 266, fa: 'مغز زردآلوی وانیلی ۵۰۰ گرم', de: 'Vanillierte Aprikosenkerne 500 g', catId: 19, catFa: 'تنقلات و آجیل', catDe: 'Snacks & Nüsse', price: 10.00, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/products/apricot-vanilla-500g.webp' },
  { id: 194, fa: 'فلفل', de: 'Paprika', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 246, fa: 'کنسرو تن ماهی', de: 'Thunfisch-Konserve', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 74,  fa: 'پودر سیر', de: 'Knoblauchpulver', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 195, fa: 'لیمو', de: 'Zitronen', catId: 22, catFa: 'سبزیجات تازه', catDe: 'Frisches Gemüse', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/broccoli.webp' },
  { id: 247, fa: 'کنسرو لوبیا', de: 'Bohnen-Konserve', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 75,  fa: 'پودر پیاز', de: 'Zwiebelpulver', catId: 9,  catFa: 'ادویه‌جات', catDe: 'Gewürze', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/spices.webp' },
  { id: 248, fa: 'کنسرو ذرت', de: 'Mais-Konserve', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
  { id: 249, fa: 'کنسرو نخودفرنگی', de: 'Erbsen-Konserve', catId: 27, catFa: 'سایر اقلام', catDe: 'Sonstiges', price: undefined, bFa: '', bDe: '', emoji: '', imgBg: '#fff', img: '/images/categories/coffee.webp' },
];

export const SERVICES: Service[] = [
  { iconName: 'Package',   fa: 'خرید حضوری',             de: 'Einkauf vor Ort',               dFa: 'فضای گرم و دلنشین برای خریدهای روزانه شما',               dDe: 'Angenehme Atmosphäre für Ihren täglichen Einkauf'        },
  { iconName: 'Leaf',      fa: 'محصولات تازه روزانه',    de: 'Täglich frische Waren',         dFa: 'هر روز محصولات تازه مستقیم از تامین‌کنندگان',             dDe: 'Täglich frische Produkte direkt von den Lieferanten'     },
  { iconName: 'Globe',     fa: 'محصولات اصیل',           de: 'Authentische Produkte',         dFa: 'محصولات اصیل ایرانی و افغانی از بهترین منابع',            dDe: 'Authentische iranische & afghanische Produkte'           },
  { iconName: 'Mail',      fa: 'سفارش ویژه',             de: 'Sonderbestellungen',            dFa: 'درخواست محصولات خاص که در فروشگاه موجود نیست',            dDe: 'Anfragen für spezielle Produkte'                         },
  { iconName: 'MapPin',    fa: 'ارسال در شهر کلن',       de: 'Lieferung in Köln',             dFa: 'ارسال سفارش فقط در محدوده شهر کلن انجام می‌شود',          dDe: 'Lieferung nur innerhalb von Köln'                        },
  { iconName: 'Cart',      fa: 'سفارش واتساپی',          de: 'WhatsApp-Bestellung',           dFa: 'سفارش آسان از طریق واتساپ و هماهنگی قیمت و جزئیات',       dDe: 'Einfach per WhatsApp bestellen — Preis & Details stimmen wir gemeinsam ab' },
];

export const BADGE_STYLE: Record<string, { bg: string; color: string }> = {
  Premium:          { bg: '#F7EDD0', color: '#9A742A' },
  Importiert:       { bg: '#E8EEEA', color: '#0E3B2A' },
  Imported:         { bg: '#E8EEEA', color: '#0E3B2A' },
  Frisch:           { bg: '#DCE9E2', color: '#166044' },
  Fresh:            { bg: '#DCE9E2', color: '#166044' },
  Beliebt:          { bg: '#F5E4DC', color: '#A32222' },
  Popular:          { bg: '#F5E4DC', color: '#A32222' },
  'Täglich frisch': { bg: '#DCE9E2', color: '#166044' },
  اصل:              { bg: '#F7EDD0', color: '#9A742A' },
  تازه:             { bg: '#DCE9E2', color: '#166044' },
  محبوب:            { bg: '#F5E4DC', color: '#A32222' },
  وارداتی:          { bg: '#E8EEEA', color: '#0E3B2A' },
  ویژه:             { bg: '#F5E4DC', color: '#A32222' },
};
